### ISSUE TITLE
[2.0] Problem with inversed `OneToOne` relationships

### ISSUE THREAD

**Issue by simondaigre** [zenstruck/foundry#655] opened 2024-06-27 15:30 UTC
Hello there,

I'm upgrading a project from 1.38 to 2.0. With the Rector rule, the upgrade is really smooth, thanks @nikophil !

I just have a minor issue, in one Factory, in the `defaults()` method, I'm doing something like this :

```
protected function defaults(): array
{
    return [
        'customer' => CustomerFactory::new()->withUser(),
    ];
}
```

And in Customer factory :
```
public function withUser(): self
{
    return $this->with(static fn (): array => ['user' => UserFactory::new()]);
}
```

With Foundry 1.38, my Customer was containing an User, since 2.0 User is always null.
Is it something deprecated or a bug ?

**Comment by nikophil** [comment] 2024-06-27 15:39
Hi @simondaigre 

> With the Rector rule, the upgrade is really smooth

nice to hear that! :blush: 

You problem definitively sounds like a bug. I'm trying to reproduce it.

**Comment by nikophil** [comment] 2024-06-27 15:52
hmm I kinda made the same thing, but everything is hydrated as expected :thinking: 
```php
// Object1Factory
    protected function defaults(): array|callable
    {
        return [
            'object2' => Object2Factory::new()->withSomeObject(),
        ];
    }

// Object2Factory
    public function withSomeObject(): static
    {
        return $this->with(static fn (): array => ['object3' => Object3Factory::new(['prop1' => 'toto'])]);
    }
```

any chance you create a public reproducer please?

**Comment by simondaigre** [comment] 2024-06-27 16:42
https://github.com/simondaigre/foundry-repro

**Comment by nikophil** [comment] 2024-06-27 16:59
ok, I confirm that there is a bug: `CustomerFactory::new()->withUser()->create();` this creates two "customers"

**Comment by mmarton** [comment] 2024-09-27 16:14
Any update on this one? I have the same issue.

**Comment by nikophil** [comment] 2024-11-22 16:12
hey @mmarton @simondaigre the bug is fied in https://github.com/zenstruck/foundry/pull/659 
would you mind to test the PR before it gets merged?

**Comment by simondaigre** [comment] 2024-11-22 16:24
Hi @nikophil, I confirm the issue is fixed with your patch, thanks !

**Comment by mmarton** [comment] 2024-11-22 16:46
Hi!

it created me a lot more errors  than I originally had :/ I will investigate more and come back with the results

with 2.2.2: Tests: 58, Assertions: 215, Errors: 3
with dev-fix/inversed-one-to-one: Tests: 58, Assertions: 67, Errors: 34.

**Comment by nikophil** [comment] 2024-11-22 16:52
Which error does it give you?

**Comment by mmarton** [comment] 2024-11-22 17:11
Only checked the first issue, but it looks like it broke every 1:1 relations i have:

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity]
class Event
{
    #[ORM\Column(type: Types::INTEGER)]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    private ?int $id = null;

    #[ORM\OneToOne(mappedBy: 'event', cascade: ['persist', 'remove'])]
    #[Assert\Valid]
    private EventLimit $eventLimit;

    public function __construct()
    {
        $this->setEventLimit(new EventLimit());
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEventLimit(): EventLimit
    {
        return $this->eventLimit;
    }

    public function setEventLimit(EventLimit $eventLimit): static
    {
        // set the owning side of the relation if necessary
        if ($eventLimit->getEvent() !== $this) {
            $eventLimit->setEvent($this);
        }

        $this->eventLimit = $eventLimit;

        return $this;
    }
}
```

```php
<?php

declare(strict_types=1);

namespace App\Entity;

use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity]
class EventLimit
{
    #[ORM\Column(type: Types::INTEGER)]
    #[ORM\Id]
    #[ORM\GeneratedValue]
    private ?int $id = null;

    #[ORM\OneToOne(inversedBy: 'eventLimit', cascade: ['persist', 'remove'])]
    #[ORM\JoinColumn(nullable: false)]
    private ?Event $event = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getEvent(): ?Event
    {
        return $this->event;
    }

    public function setEvent(Event $event): static
    {
        $this->event = $event;

        return $this;
    }
}
```

```php
<?php

declare(strict_types=1);

namespace Tests\Factory;

use App\Entity\Event;
use Zenstruck\Foundry\Persistence\PersistentProxyObjectFactory;

/**
 * @extends PersistentProxyObjectFactory<Event>
 */
final class EventFactory extends PersistentProxyObjectFactory
{
    public static function class(): string
    {
        return Event::class;
    }

    protected function defaults(): array
    {
        return [
            'eventLimit' => EventLimitFactory::new(),
        ];
    }
}
```

```php
<?php

declare(strict_types=1);

namespace Tests\Event;

use Symfony\Bundle\FrameworkBundle\Test\KernelTestCase;
use Tests\Factory\EventFactory;
use Zenstruck\Foundry\Test\Factories;
use Zenstruck\Foundry\Test\ResetDatabase;

class EventdTest extends KernelTestCase
{
    use Factories;
    use ResetDatabase;

    public function testIssue(): void
    {
        $event = EventFactory::createOne();
        self::assertTrue(true);
    }
}
```

```
There was 1 error:

1) Tests\Event\EventTest
Symfony\Component\PropertyAccess\Exception\InvalidTypeException: Expected argument of type "App\Entity\EventLimit", "null" given at property path "eventLimit".

/var/www/html/vendor/symfony/property-access/PropertyAccessor.php:198
/var/www/html/vendor/symfony/property-access/PropertyAccessor.php:124
/var/www/html/vendor/zenstruck/foundry/src/Object/Hydrator.php:68
/var/www/html/vendor/zenstruck/foundry/src/Object/Instantiator.php:48
/var/www/html/vendor/zenstruck/foundry/src/ObjectFactory.php:59
/var/www/html/vendor/zenstruck/foundry/src/Persistence/PersistentObjectFactory.php:195
/var/www/html/vendor/zenstruck/foundry/src/Persistence/PersistentProxyObjectFactory.php:41
/var/www/html/vendor/zenstruck/foundry/src/Factory.php:63
/var/www/html/vendor/zenstruck/foundry/src/Persistence/PersistentProxyObjectFactory.php:50
/var/www/html/tests/Event/EventTest.php:27

Caused by
TypeError: App\Entity\Event::setEventLimit(): Argument #1 ($eventLimit) must be of type App\Entity\EventLimit, null given, called in /var/www/html/vendor/symfony/property-access/PropertyAccessor.php on line 532
```

**Comment by nikophil** [comment] 2024-11-22 17:20
yes thanks for this, I do see where it comes from, and I currently have no solution, have to dig a little bit more
https://github.com/zenstruck/foundry/pull/659#discussion_r1658634353

**Comment by nikophil** [comment] 2024-11-29 16:55
ok, this problem is really hard to fix... I've found a solution, that MIGHT work, but I'm not so proud of it :sweat_smile: 

Could you test this PR https://github.com/zenstruck/foundry/pull/726 :pray:  @simondaigre  @mmarton 

(I've not managed to reproduce your problem with our fixtures, I'm gonna give another try)

thanks!

**Comment by mmarton** [comment] 2024-11-30 16:06
Hi!

Thank you for your work.
I'm pretty busy atm, I will test it and get back with the results in a couple days and create a reproducer demo if necessary.

**Comment by simondaigre** [comment] 2024-11-30 18:42
@nikophil Still OK for me :+1:

**Comment by nikophil** [comment] 2024-12-01 17:08
I've managed to reproduce your problem in the tests! I think you won't need to create any reproducer app :crossed_fingers:

**Closed as completed** 2024-12-04 12:58 UTC
Labels: bug
