### ISSUE TITLE
ManyToMany relationships

### ISSUE THREAD

**Issue by AlexandreGerault** [zenstruck/foundry#421] opened 2023-02-16 17:14 UTC
Hi!

I've been trying to use this bundle to setup some of my integration test. I used to use factory classes a lot in my Laravel projects which look very similar to this bundle.

It looks great, however I can't setup a many to many relationship. I tried to folllow what the doc says, but it results in an error.

Here's the test:
```php
class IssueWithManyToManyTest extends KernelTestCase
{
    use Factories;
    use ResetDatabase;

    public function testManyToManyWithFoundrySetup(): void
    {
        $post = PostFactory::new()->create();

        $tag = TagFactory::new()->create(['posts' => [$post]]);
    }
}
```
with the following entities
```php
#[Entity]
#[Table(name: 'post')]
class Post
{
    #[Id]
    #[GeneratedValue]
    #[Column(type: Types::INTEGER)]
    public int $id;

    #[ManyToMany(targetEntity: Tag::class, inversedBy: 'posts')]
    public Collection $tags;

    #[Column(type: Types::STRING)]
    public string $title;

    #[Column(type: Types::TEXT)]
    public string $content;

    public function __construct()
    {
        $this->tags = new ArrayCollection();
    }
}
```
and
```php
#[Entity]
#[Table(name: 'tag')]
class Tag
{
    #[Id]
    #[GeneratedValue]
    #[Column(type: Types::INTEGER)]
    public int $id;

    #[ManyToMany(targetEntity: Post::class, mappedBy: 'tags')]
    public Collection $posts;

    #[Column(type: Types::STRING)]
    public string $name;

    public function __construct()
    {
        $this->posts = new ArrayCollection();
    }
}
```

When running the tests, I'm obtaining
```
Symfony\Component\PropertyAccess\Exception\InvalidArgumentException: Expected argument of type "Doctrine\Common\Collections\Collection", "array" given at property path "posts".
/home/projects/foundry-issue/vendor/symfony/property-access/PropertyAccessor.php:530
/home/projects/foundry-issue/vendor/symfony/property-access/PropertyAccessor.php:130
/home/projects/foundry-issue/vendor/zenstruck/foundry/src/Instantiator.php:76
/home/projects//foundry-issue/vendor/zenstruck/foundry/src/Factory.php:119
/home/projects//foundry-issue/tests/IssueWithManyToManyTest.php:22

Caused by
TypeError: Cannot assign array to property App\Entity\Tag::$posts of type Doctrine\Common\Collections\Collection

/home/projects/foundry-issue/vendor/symfony/property-access/PropertyAccessor.php:530
/home/projects/foundry-issue/vendor/symfony/property-access/PropertyAccessor.php:130
/home/projects/foundry-issue/vendor/zenstruck/foundry/src/Instantiator.php:76
/home/projects/foundry-issue/vendor/zenstruck/foundry/src/Factory.php:119
/home/projects/foundry-issue/tests/IssueWithManyToManyTest.php:22
```

Here's [a repository that reproduce](https://github.com/AlexandreGerault/foundry-issue) my error. I tried [code explained in the doc](https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#many-to-many) as well, but still get the same error.

**Comment by kbond** [comment] 2023-02-16 20:16
Interesting, I believe the issue is your `$posts`/`$tags` fields are public. When creating the factory it is trying to set the array of tags directly to the `Collection`.

I believe will be fixed with #312 which will convert arrays to collections automatically.

As a current solution, there are two options:
1. `$tag = TagFactory::new()->create(['posts' => new ArrayCollection([$post])]);`
2. Add `addPost`/`removePost` methods to Tag and `addTag`/`removeTag` methods to Post (this is what the symfony/maker-bundle generates.

As an aside, the reason this hasn't come up before is typically you want to "protect" your relationship collections (make them private and only accessible/modifiable via getters/adders/removers). I think your code is fundamentally flawed. For instance, the following is possible with your current setup:

```php
$post = $em->find(Post::class, 1);
$post->tags->add('some random thing');

$em->flush(); // doctrine blows up!
```

Even if you add the correct tag object, it doesn't set the owning side automatically. See [this doc](https://symfony.com/doc/current/doctrine/associations.html) for more information. Again, using the maker-bundle will generate code that works seamlessly with Foundry.

**Comment by AlexandreGerault** [comment] 2023-02-16 22:46
Doing so (adding getter/setter and add/remove methods for collections) resolved the error.

But the many to many tables stay empty... That is what I used to have when applying your first suggestion. Though, I thought it was due to a wrong use of factories (as passing an ArrayCollection is not documented directly in doc)

If I debug the post created by the factory, it has tags. But fetching it from DB, it has no tag. Looking to association table manually, it does not have associations

**Comment by kbond** [comment] 2023-02-16 22:49
Does the tags/posts table have the expected rows?

**Comment by AlexandreGerault** [comment] 2023-02-16 22:50
Yes they have

EDIT: should I update the demo repo?

**Comment by kbond** [comment] 2023-02-16 22:50
What does your adder look like?

**Comment by AlexandreGerault** [comment] 2023-02-16 22:55
For the tag I have this:

| id | name                                                                                                                         |
|----|------------------------------------------------------------------------------------------------------------------------------|
| 1  | Vel autem sint sit est vel modi est. Non fugiat dolore illo exercitationem quae. Asperiores cum earum alias quae eveniet et. |


For the post I have this:

| id | title                                                                                                                            | content                                                                                                                                                     |
|----|----------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------|
| 1  | Architecto ipsum totam maiores autem sunt. Numquam accusamus non consequatur ea dolorum totam. At voluptas dolor sunt aut nulla. | Fugiat voluptatem quidem praesentium et omnis. Ipsum pariatur dignissimos dolores blanditiis. Nihil provident quod ipsam dolor numquam debitis perferendis. |

And finally the association table:
| post_id | tag_id |
|---------|--------|

**Comment by kbond** [comment] 2023-02-16 22:58
Sorry, I meant what does your `Post::addTag()` and/or `Tag::addPost()` method(s) look like.

> should I update the demo repo?

Sure, could help me diagnose the issue.

**Comment by AlexandreGerault** [comment] 2023-02-16 23:01
Sure, repo updated and here are the methods:

```php
public function getTags(): Collection
{
    return $this->tags;
}

public function setTags(Collection $tags): self
{
    $this->tags = $tags;

    return $this;
}

public function addTag(Tag $tag): self
{
    if (!$this->tags->contains($tag)) {
        $this->tags->add($tag);
    }

    return $this;
}

public function removeTag(Tag $tag): self
{
    if ($this->tags->contains($tag)) {
        $this->tags->removeElement($tag);
    }

    return $this;
}
```

**Comment by kbond** [comment] 2023-02-17 00:09
Ok, the issue is you're not setting the inverse side in your adders. Changing them to:

```php
public function addTag(Tag $tag): self
{
    if (!$this->tags->contains($tag)) {
        $this->tags->add($tag);
        $tag->addPost($this);
    }

    return $this;
}
```

```php
public function addPost(Post $post): self
{
    if (!$this->posts->contains($post)) {
        $this->posts->add($post);
        $post->addTag($this);
    }

    return $this;
}
```

Should fix the problem. Let me know if it doesn't.

**Comment by AlexandreGerault** [comment] 2023-02-17 06:25
Thanks a lot, you figured it out. I would never thought about this!

Should I propose a bit of documentation for many to many section or should we be aware of this when using doctrine? I don't remember reading such information about this as a Symfony beginner and I think it could help other in future.

Maybe it also depends on the PullRequest #312. Just let me know :+1:

**Closed as completed** 2023-02-17 06:26 UTC

**Comment by nikophil** [comment] 2023-02-17 09:23
Hi @AlexandreGerault 

you can find "good practices" about this in Symfony documentation. This specific paragraph concerns your problem: https://symfony.com/doc/current/doctrine/associations.html#setting-information-from-the-inverse-side

This page is already linked in Foundry's doc here: https://symfony.com/bundles/ZenstruckFoundryBundle/current/index.html#doctrine-relationships

Still, maybe we could add a small `tip` at the end of `ManyToMany` paragraph, which says something like the following, I think some people could find this useful
```rst
When using `OneToMany` or `ManytoMany` relationships, it is recommended to add proper adders [link to the Symfony docs]
```

**Comment by AlexandreGerault** [comment] 2023-02-17 10:13
If adding this little sentence is welcomed, I'd gladly create the corresponding PR :+1:

**Comment by nikophil** [comment] 2023-02-17 10:56
I'd say: if you do estimate that it would have helped you, this is welcomed!

I think this "inverse side" stuff could be quite complex, and even if the page is already linked in Foundry's docs, it is quite long, so a link to the specific paragraph, inside the right section would be nice to have
