### ISSUE TITLE
bug: infinite loop when 2 factories refer to each other in their `default()` methods

### ISSUE THREAD

**Issue by simondaigre** [zenstruck/foundry#724] opened 2024-11-22 16:47 UTC
Since 2.x on one of my projects, I have a segfault when I try to create a complex `PersistentProxyObject` with a lot of dependencies. 
On 1.x no issues at all.

I dig a lot to find what's wrong but I have no clue. 
Reproducer is here : https://github.com/simondaigre/foundry-repro/tree/repro-segfault

**Comment by nikophil** [comment] 2024-11-22 16:56
Ok, thanks for the reproducer, I'll check this when I got some time

**Comment by kbond** [comment] 2024-11-22 20:16
@simondaigre, 404 when accessing your reproducer. Maybe not public?

**Comment by simondaigre** [comment] 2024-11-22 20:39
> @simondaigre, 404 when accessing your reproducer. Maybe not public?

You're right, I just made it public.

**Comment by nikophil** [comment] 2024-12-12 09:47
hi @simondaigre 

the problem is not a "complex schema" or a lot of dependencies.
You have an infinite loop:
```php
final class AgencyFactory extends PersistentProxyObjectFactory
{
    protected function defaults(): array
    {
        return [
            'agencyImages' => AgencyImageFactory::new()->many(self::faker()->randomDigitNotNull()),
        ];
    }
}

final class AgencyImageFactory extends PersistentProxyObjectFactory
{
    protected function defaults(): array
    {
        return [
            'agency' => AgencyFactory::new(),
        ];
    }
}
```

when I do `dump(static::class)`, It prints infinitely:
```
^ "App\Factory\AgencyFactory"
^ "App\Factory\AgencyImageFactory"
^ "App\Factory\AgencyFactory"
^ "App\Factory\AgencyImageFactory"
^ "App\Factory\AgencyFactory"
^ "App\Factory\AgencyImageFactory"
...
```

As stated in the docs, you should avoid adding `...ToMany` relationships in the `defaults()` method:
![Capture d’écran du 2024-12-12 10-39-57](https://github.com/user-attachments/assets/b087f198-fade-4c7a-b4e7-0358beb0dff2)

That being said, I think we should implement some kind of circular dependency guard. 

I'm also wondering how Foundry 1 did handle this :thinking:

**Comment by simondaigre** [comment] 2024-12-12 10:02
@nikophil thanks for looking at this !

I can handle this but it could be simpler if Foundry handle this. Sometime I just need to instanciate some `AgencyImage`, sometimes I need `Agency` instance with `AgencyImage`.

I tried to remove `AgencyImage` and upgrade to Foundry 2 and now I have a lot of `A new entity was found through the relationship xxx that was not configured to cascade persist operations.` on other tests. I'll check this new issue later.

**Comment by nikophil** [comment] 2024-12-12 10:23
> I can handle this but it could be simpler if Foundry handle this. Sometime I just need to instanciate some AgencyImage, sometimes I need Agency instance with AgencyImage.

I'm not sure we'll actively support the fact to add `OneToMany` in the `default()` method. I'll have to think about it, but it used to lead to surprising results in Foundry 1 (unfortunately I cannot find the issue where this was stated). 

> I tried to remove AgencyImage and upgrade to Foundry 2 and now I have a lot of A new entity was found through the relationship xxx that was not configured to cascade persist operations. on other tests. I'll check this new issue later.

you can either add `cascade: ['persist']` to your relationships. Or wait for https://github.com/zenstruck/foundry/pull/742 to be released. I think it will fix your problems

**Comment by nikophil** [comment] 2024-12-12 10:34
fun fact: https://github.com/zenstruck/foundry/pull/742 seems to also fix the infinite loop problem, and I absolutely don't know why :sweat_smile: 

by the way, I tried to reproduce the problem in foundry's test suite, and I did not manage to do it, even without the fix :shrug:

**Comment by simondaigre** [comment] 2024-12-12 10:41
I just checked and I confirm #742 fixes all my issues. All my tests are OK, like Foundry 1 :tada:

**Comment by nikophil** [comment] 2024-12-12 10:43
this will be released soon :wink:

**Closed as completed** 2024-12-14 12:08 UTC
Labels: bug
