### ISSUE TITLE
No object manager registered when creating objects than are not entities

### ISSUE THREAD

**Issue by ndench** [zenstruck/foundry#314] opened 2022-10-13 02:00 UTC
I'm trying to create some DTO objects (ie. _not_ an entity). The docs say that we can call `withoutPersisting()`, however that is still resulting in a RuntimeException:

```
RuntimeException : No object manager registered for "App\Model\Foo".
```

I've tried calling `withoutPersisting` from both in the factory's `initialize()` method, and also when consuming the Factory.

```php
final class FooFactory extends ModelFactory
{
    protected function getDefaults(): array
    {
        return [
            'id'   => self::faker()->uuid(),
        ];
    }

    protected function initialize(): static
    {
        return parent::initialize()->withoutPersisting();
    }

    protected static function getClass(): string
    {
        return Foo::class;
    }
```

```php
$model = FooFactory::new()->withPersisting()->create();
```

From looking at [Factory.php](https://github.com/zenstruck/foundry/blob/619987f70cbc12952f3363e35a4514149ce79699/src/Factory.php#L347) it appears that it will always look for an object manager, regardless of whether `withoutPersisting()` has been called or not.

Am I missing something here?

**Comment by nikophil** [comment] 2022-10-13 07:23
Hello,

I'm surprised since I'm using a lot this feature (ie: using foundry on plain PHP objects).

There is no error in your code (BTW no need to call `parent::initialize()` in initialize...).
Would you mind to create a reproducer somewhere?

**Comment by kbond** [comment] 2022-10-13 15:41
I quickly tried to reproduce but couldn't.

**Comment by nikophil** [comment] 2022-11-02 08:26
Hi,

I'm closing this issue, since we cannot reproduce it.

**Closed as completed by nikophil** 2022-11-02 08:26 UTC
